Main svc
Seva144/java-explore-with-me pull request #4
Opened 2023-06-13 23:24 UTC by Seva144

2023-06-14 11:07 UTC, ErkinKasymaliev requested changes
привет, неплохо!
Оставил комменты

2023-06-14 11:07 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/main_service/services/impl/EventServiceImpl.java
> +    public Map<Long, Long> getViewStats(Collection<Event> eventList) {
методы, которые используете внутри класса, лучше сделать private

2023-06-14 19:34 UTC, Seva144 commented
Добрый вечер! исправил по замечаниям

2023-06-15 12:50 UTC, ErkinKasymaliev approved these changes
привет!
Работа принята

2023-06-15 18:53 UTC, merged